version: "3.7"
name: phantom

include:
  - ../docker-compose.networks.yml
  - ../docker-compose.volumes.yml

services:
  auto-m4b:
    # image: seanap/auto-m4b
    # build: https://github.com/brandonscript/auto-m4b.git
    # stdin_open: true # docker run -i
    # tty: true # docker run -t
    build:
      context: .
      args:
        PUID: 1000
        GUID: 1000
    container_name: auto-m4b
    restart: unless-stopped
    volumes:
      - /etc/docker/auto-m4b/:/config:rw
      # - /etc/docker/auto-m4b/auto-m4b-tool.sh:/auto-m4b-tool.sh:ro
      - ragnarok-media:/media:rw
      # - downloads:/path/to/mount/downloads:rw
    networks:
      - bridge
    environment:
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - MAX_CHAPTER_LENGTH=15,30
      - INBOX_FOLDER=/media/Downloads/#done/#books/#convert/inbox
      - CONVERTED_FOLDER=/media/Downloads/#done/#books/#convert/converted
      # - CONVERTED_FOLDER=/media/Books/Audiobooks/_Updated plex copies
      - ARCHIVE_FOLDER=/media/Downloads/#done/#books/#convert/processed
      - FIX_FOLDER=/media/Downloads/#done/#books/#convert/fix
      - BACKUP_FOLDER=/media/Downloads/#done/#books/#convert/backup
      - WORKING_FOLDER=/tmp/auto-m4b
      - OVERWRITE_EXISTING=Y
      - MAKE_BACKUP=Y
      - SKIP_COVERS=N
      - NO_FIX=Y
      - DEBUG=Y
      - TZ=America/Vancouver
# volumes:
#   downloads:
#     driver_opts:
#       type: cifs
#       o: username={username},password={password},uid=1000,gid=1000,vers=3.0,rw
#       device: //{nas-ip-address}/{share-name}
